version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: ${COMPOSE_PROJECT_NAME}_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - ./app/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - backend_network
  
  playlists_api:
    build: .
    container_name: ${COMPOSE_PROJECT_NAME}_api
    restart: unless-stopped
    environment:
      MONGODB_URI: "mongodb://${MONGO_APP_USERNAME}:${MONGO_APP_PASSWORD}@playlists_app_mongodb:27017/${MONGO_INITDB_DATABASE}?authSource=${MONGO_INITDB_DATABASE}"
      FLASK_ENV: ${FLASK_ENV}
      LOG_LEVEL: ${LOG_LEVEL}
    depends_on:
      - mongodb
    networks:
      - backend_network
      - nginx_api_network
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - nginx_api_network
    depends_on:
      - playlists_api

volumes:
  mongodb_data:

networks:
  backend_network:
    driver: bridge
  nginx_api_network:
    driver: bridge